### ISSUE TITLE
Pantheon Mail, Number of messages in thread not showing up

### ISSUE THREAD

**Issue by ryanleesipes** [system76/pop-gtk-theme#1]
The below circles should be a "2" and a "4" respectively, but they are obscured. I'm not sure what is causing this, but it makes for a not very great experience. Not sure if this problem exists in any other software, I have not yet observed it.

![screenshot from 2017-04-26 18-12-34](https://cloud.githubusercontent.com/assets/2141621/25462430/1ec7f58c-2aac-11e7-8cfa-671bcbb2273c.png)

**Comment by WatchMkr** [comment]
This occurs in others GTK themes. Also, doesn't happen in Geary. Should be filed against Pantheon.
