### ISSUE TITLE
Cut off the button shadow

### ISSUE THREAD

**Issue by Corsseir** [system76/pop-gtk-theme#10]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
 * Desktop environment - 
 * Pop version - (run ```apt policy pop-gtk-theme```)
 ```

**Related Application and/or Shell theming (or name of widget)**
GNOME Photos

**Actual issue**
Cut off the button shadow in GNOME Photos.

![3](https://user-images.githubusercontent.com/11137173/29239300-ca70e1e8-7f4b-11e7-9d6c-d0b99a86e739.png)

**Steps to reproduce**

**Expected behavior**

**Behavior in Adwaita**

**Other Note (feature-request, question, etc...)**

**Comment by Corsseir** [comment]
I have updated today the pop-gtk-theme but this bug still persist.

**Comment by isantop** [comment]
Can you send in the output of `head -5 /usr/share/themes/Pop/gtk-3.22/gtk.css`
