### ISSUE TITLE
weird shades in the firefox tabs

### ISSUE THREAD

**Issue by elopio** [system76/pop-gtk-theme#12]
There are some weird shades on the firefox tabs. Take a look at the attached image at the bottom.

```
 * Distribution: Ubuntu Gnome, 17.04
 * Gtk+ 3.0 version: 3.22.11-0ubuntu3
 * Desktop environment:  gnome-shell 3.24.0-0ubuntu2
 ```
**Steps to reproduce**

Install the pop theme from the PPA and enable it as explained in http://blog.system76.com/post/160445549288/gnome
Open multiple tabs of firefox.
Check the sides of the selected tab.

**Expected behaviour**

No shades on top of the selected tab.

![issues system76-pop-gtk-theme - mozilla firefox_008](https://cloud.githubusercontent.com/assets/617831/25819260/a99ad0e8-33ea-11e7-9fb2-7def4a1eb892.png)

**Comment by isantop** [comment]
I think this may be caused by the anti-aliasing Firefox uses when drawing its fancy curved tabs. Could you try grabbing a screenshot using another theme (Adwaita would be fine) just to confirm that this is a Pop issue?

**Comment by elopio** [comment]
It's weirder now because it's not happening anymore. I'll close it until I can figure out how to reproduce it.

Thanks.

**Comment by elopio** [comment]
I could reproduce this in a new machine. Apparently, it happens just the first time I select the theme. When I select adwaita back, the shades go away. To solve it, I restarted.

Attached is a video that shows the problem. I'll reopen this bug.

[out-1.zip](https://github.com/system76/pop-gtk-theme/files/1055353/out-1.zip)

**Comment by isantop** [comment]
There are a few weird issues that can crop up when switching themes. This is especially true with Firefox, since it doesn't use GTK (instead it parses the GTK theme and tries to skin its own UI to match that). If it works fine in cases where the theme wasn't just previously switched, then I don't think there's any way we can fix it. It's likely a Firefox bug at that point.
