### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by carlwgeorge** [system76/pop-gtk-theme#16]
Can the project please start tagging releases?  The [tags that exist seem to be carried over from Adapta](https://github.com/system76/pop-gtk-theme/tags).  Those versions (3.90.0.81, 3.90.0.78, etc) are clearly not the same style as the version defined in the [`configure.ac` file](https://github.com/system76/pop-gtk-theme/blob/master/configure.ac#L1-L3) (1.1.1, 1.2.0, etc).

**Comment by isantop** [comment]
Thanks for opening this issue! Generally, releases are provided through the PPA releases. We'll begin tagging releases through Github as well.
