### ISSUE TITLE
[Xfce4] Gtk3 and some Gtk2 Applet background aren't the same color as the rest of the xfce4-panel

### ISSUE THREAD

**Issue by jristz** [system76/pop-gtk-theme#18]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.12+6+g42aa4c138c-1
 * Gtk+ 2.0 version - 2.24.31
 * Desktop environment - Xfce4
 ```

**Adapta version (if you knew)**
Using stable 1.0.8-1
Using latest git from master branch

**Related Application and/or Shell theming (or name of widget)**
Stable xfce4-panel with some gtk3 applets (clipman, xfce4-pulseaudio-plugin, battery-plugin)

**Actual issue**
The zone where the applets are placed are ofa colour far different from the one on the pannel.

**Steps to reproduce (if you knew)**
Use xfce4-panel with some applets.

![captura de pantalla_2017-05-09_22-02-06](https://cloud.githubusercontent.com/assets/855726/25878712/cbb24b82-34fa-11e7-8322-f96a113f9ff7.png)

**Expected behaviour**
All the pannel indifferent from the applet remain with the same base colour as the rest of the pannel.

**Other Note (feature-request, question, etc...)**
Notes: maybe is rellated to the small color difference in windows in issue #10

**Comment by isantop** [comment]
I don't think this is related to #10 because that was due to a change made to the gtkrc files that wasn't mirrored to the SVG files for the window borders in xfwm. Additionally, in Xubuntu 17.04 this issue doesn't seem to appear, so it may be something weird about how those widgets are drawn on the panel. 

_Please note that while the Non-GNOME tag has been applied to this issue, this does not me it will not be fixed._

**Comment by jristz** [comment]
ok no problem, anyway, I did some basic checks and the only applets affected are gtk3 applets, gtk2 applet like keyboard (first screenshoot) aren't affected.
So probably when xfce4-panel in gtk3 emerge in the next xfce4 release this will be easier to detect the issue.

**Comment by isantop** [comment]
After merging Upstream Adapta, this issue doesn't seem to happen. Calling this fixed for now.

**Comment by jristz** [comment]
I'm sorry but

the bug remain only in pop theme but now it only happend with gtk3 applets separated from systray (like battery and pulseaudio volume).
