### ISSUE TITLE
[MATE] Issue with dividers on panels

### ISSUE THREAD

**Issue by emptythevoid** [system76/pop-gtk-theme#19]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.04 64-bit
 * Gtk+ 3.0 version - libgtk-3-0:amd 3.22.11-0ubu
 * Desktop environment - MATE
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**
Panels in MATE

**Actual issue**
When the Pop theme is active, the dividers (I don't know what else to call them) on MATE panels are not visible.  This can cause unexpected behavior if you're trying to modify the panels but cannot see the dividers (for example, if you're making a new bottom panel, and want a "show desktop" icon on the far left, and then want the Window List to appear right next to it, you'd have to turn off the Pop theme to be able to see the divider to move the Window List over next to the "show desktop" icon - otherwise it's stuck in the center of the panel).  Switching to a different theme that allows the divider to be visible works around the problem.

**Steps to reproduce (if you knew)**
1.) Enable Pop theme
2.) Delete panel
3.) Create new panel
4.) Add Show Desktop to panel; move icon to the far left
5.) Add Window List to panel; attempt to move to far left, next to Show Desktop

See this Youtube screencast to see the issue:  https://www.youtube.com/watch?v=Micc0x4Wclc

**Expected behaviour**
You should see the divider line to the left of the Window List as it appears on the panel.  Right-clicking this allows you to move the position of the Window Picker.  

**Other Note (feature-request, question, etc...)**
The "divider" is not to be confused with the Separator you can add to the panel.  That's not what I'm talking about.

Edit: Small clarification in wording

**Comment by isantop** [comment]
Thanks for filing this issue! I'll have to dig into that a bit to figure out what that widget is called.

**Comment by emptythevoid** [comment]
Absolutely welcome.  What could I provide you to help out further?  I *think* the widget is simply "mate-panel"  http://manpages.ubuntu.com/manpages/zesty/man1/mate-panel.1.html

**Comment by emptythevoid** [comment]
Also, FWIW, this issue isn't specific to the Pop theme.  There are several other control themes that seem to make that divider invisible.

**Comment by emptythevoid** [comment]
Oooh, maybe found something.  One of the themes that *does* work is the Ambiant-MATE theme.  Inside /usr/share/themes/Ambiant-MATE/gtk-3.0/apps/assets is a single file called panel-grid.svg that *appears* to be the divider (attached as zip) 
[panel-grid.svg.zip](https://github.com/system76/pop-gtk-theme/files/1002228/panel-grid.svg.zip)
