### ISSUE TITLE
GTK 2.0 menus render light gray text on white background

### ISSUE THREAD

**Issue by strycore** [system76/pop-gtk-theme#2]
**Reporter info**

On GTK2 apps (like Hexchat), menus have a really low contrast with really light gray text on white background. 

![selection_001](https://cloud.githubusercontent.com/assets/280336/25512463/c87498f2-2b82-11e7-9cd3-b4a45b96dd03.png)

 ```
 * Distribution - Ubuntu 17.04
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Gnome Shell
 ```

**Related Application and/or Shell theming (or name of widget)**

Hexchat / Other GTK2 apps. Menus

**Expected behaviour**

High contrast colors, like on GTK3 apps

**Comment by strycore** [comment]
This also applies to inactive tabs and some dialog boxes:

![612 b b e - trance forever vol 1 - anthems - seven days and one week 08 27 - audacious_002](https://cloud.githubusercontent.com/assets/280336/25512620/fc63d3fc-2b83-11e7-8ced-66899e80d77b.png)

**Comment by strycore** [comment]
I've noticed this is an issue with the Adapta theme as well, should I report it there instead?

**Comment by strycore** [comment]
This patch fixes the issue, I can make a PR if needed

```
--- colors.rc.in.txt	2017-04-27 20:24:40.317024704 -0700
+++ colors.rc	2017-04-27 20:28:52.911720980 -0700
@@ -1,8 +1,8 @@
 #
 # Colour scheme
 #
-gtk-color-scheme = "base_color:#FFFFFF\nbg_color:#FAFBFC"
-gtk-color-scheme = "text_color:#263238\nfg_color:#263238"
+gtk-color-scheme = "base_color:#444A58\nbg_color:#404552"
+gtk-color-scheme = "text_color:#F7F9F9\nfg_color:#263238"
 gtk-color-scheme = "selected_bg_color:#00BCD4\nselected_fg_color:#FFFFFF"
 gtk-color-scheme = "tooltip_bg_color:#222D32\ntooltip_fg_color:#CFD8DC"
 gtk-color-scheme = "link_color:#03A9F4\nvisited_link_color:#9C27B0"
```

**Comment by isantop** [comment]
Thanks for that report! A PR would be great, thanks!
