### ISSUE TITLE
Evince zoom control percentage is overlapped by other widgets

### ISSUE THREAD

**Issue by Feichtmeier** [system76/pop-gtk-theme#2]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - Ubuntu GNOME 17.04
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - GNOME
 * Pop version - 2.0.1.0
 ```

**Related Application and/or Shell theming (or name of widget)**
Evince page text areas overlap and the buttons look like a plat above the applications not the material way like in adapta with just one line. I added a screenshot comparison for both evince and gnome tweak as an button example. You can also see the doted lines in the pop gtk evince screenshot

![bildschirmfoto vom 2017-08-05 00-09-02](https://user-images.githubusercontent.com/15329494/28988914-8946d508-7972-11e7-82c7-a1bda281953b.png)
![bildschirmfoto vom 2017-08-05 00-02-56](https://user-images.githubusercontent.com/15329494/28988913-8945a5f2-7972-11e7-8443-71a0131bc9a3.png)
![bildschirmfoto vom 2017-08-05 00-04-01](https://user-images.githubusercontent.com/15329494/28988915-89494bc6-7972-11e7-9ceb-e55e9f029823.png)
![bildschirmfoto vom 2017-08-05 00-04-11](https://user-images.githubusercontent.com/15329494/28988916-894a994a-7972-11e7-97df-ce08bd96a92e.png)

![bildschirmfoto von 2017-08-05 00-02-45](https://user-images.githubusercontent.com/15329494/28988752-b94ed6c0-7971-11e7-8bc2-c6b4329d6df8.png)

**Actual issue**

**Steps to reproduce**

**Expected behavior**

**Behavior in Adwaita**

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
Regarding the styling for GtkEntry, GtkComboEntry, and other related widgets, the new styling is a deliberate design choice to help ensure the usability of these components. The old look was lighterweight, but it was difficult to tell that these widgets were there, particularly with many other widgets around. 

The percentage issue is Evince is definitely a problem. We'll have to look into the best way to fix it.

**Comment by Feichtmeier** [comment]
Maybe this good fix the dotted lines issue:

https://www.reddit.com/r/Fedora/comments/3cnxuv/how_to_get_rid_of_dotted_line_in_gtk3_apps/

**Comment by isantop** [comment]
I don't think that the overshoot is causing that. Regardless, turning off the overshoot isn't the right way to fix that. I'll have a look today and see if I can find any dashed lines in the theme.

**Comment by isantop** [comment]
So, learning to read properly would greatly advance my professional image. That post said _under_shoot, which was still enabled. They have been removed as of 4185463622da49258aafee28b06a0c78bc904b57

**Comment by isantop** [comment]
Evince (and other Entry clipping applications) are now fixed in d6eeb9fc5695a7246b4d60d42c85122b581d77a6

**Comment by Feichtmeier** [comment]
Yay that worked, ty! Somehow that commit changed te overlapping of the current page and total page count text fields top =] ✓

**Comment by Feichtmeier** [comment]
Yay that worked, ty! Somehow that commit fixed  te overlapping of the current page and total page count text fields too =] ✓ sorry for double post
