### ISSUE TITLE
GTK2 inactive scrollbars are an ugly peach color

### ISSUE THREAD

**Issue by bencates** [system76/pop-gtk-theme#20]
![Java example](https://cloud.githubusercontent.com/assets/431849/26009773/7c465188-3707-11e7-94c6-9f60bd76bb70.png)
![native GTK2 example](https://cloud.githubusercontent.com/assets/431849/26009774/7c545b98-3707-11e7-82f4-754807fec5dc.png)

**Comment by isantop** [comment]
Fixed with rebase on upstream Adapta in f9e32021b3172a5cab08970441582183e318afa0
