### ISSUE TITLE
Can't resize windows horizontally

### ISSUE THREAD

**Issue by fralix** [system76/pop-gtk-theme#22]
**Reporter info**

```
 * Distribution: Debian 9.1
 * Gtk+ 3.0 version: 3.22.11-1
 * Desktop environment: MATE 1.16.2
 * Pop version: Pulled from git and used ./install.sh (latest)
 ```

**Actual issue**
I cannot resize windows horizontally with the pop themes. Vertically is possible.
Works correctly with other Themes.

**Steps to reproduce**
Install Pop Theme and try to resize a window horizontally

**Expected behavior**
Resize Cursor appearing when at the border of the window. Moving when clicked resizes the window.

**Behavior in Adwaita**
Same behavior in Adwaita.

**Comment by isantop** [comment]
This sounds like a bug with MATE's window manager. It sounds like it doesn't correctly handle borderless windows. Unfortunately, this isn't within the scope of the theme to fix.
