### ISSUE TITLE
YUGE padding on buttons in Inkscape (Trunk) with GTK3

### ISSUE THREAD

**Issue by rolandixor** [system76/pop-gtk-theme#22]
**Reporter info**

 * Ubuntu 16.10
 * Gtk+ 3.20
 * KDE 5.8

Pop version: Not certain, I had to use the Noobslab PPA as the system76 PPA doesn't support my distro (and I'm not ready to upgrade yet).

**Application:**
Inkscape.

**Actual issue**
Massive padding around buttons in fill and stroke and other such dialogs/tabs.

**Steps to reproduce (if you knew)**
Use Inkscape GTK3.

**Expected behaviour**
Less padding.

**Behaviour in Adwaita**
No such gigantic padding.

**Comment by rolandixor** [comment]
![-new document 1 - inkscape_402](https://cloud.githubusercontent.com/assets/558147/26191383/abd5eada-3b7b-11e7-98a4-42451b187980.png)

**Comment by isantop** [comment]
I can make the padding smaller, but this doesn't reduce the minimum dock size. The dock (sidebar with options on the right) seems to have its size hardcoded into Inkscape's logic, so this will need to be fixed upstream. Even with the padding on all buttons reduced to 0, the dock can't be resized to a more reasonable value.

![screenshot from 2017-05-23 10-38-15](https://cloud.githubusercontent.com/assets/5883565/26365224/2a928910-3fa4-11e7-9dfc-c46a09156aef.png)

**Comment by rolandixor** [comment]
That's weird, because if I use a different theme, it doesn't happen (even if the theme uses padding on buttons).
![full - the battle is on 3 svg - inkscape_403](https://cloud.githubusercontent.com/assets/558147/26365333/53ba3962-3fb5-11e7-9ea6-be2320c7efd2.png)

**Comment by rolandixor** [comment]
Oh btw... you have transform open - that dock is huge and will force all others to be gigantic. Try resizing your other docks with transform closed or minimized and see what happens.

**Comment by isantop** [comment]
Yeah, I figured that out shortly afterwards.

I did tweak the padding to tighten up the interface a bit. These are available in d2aed5e1, so I'm going to call this closed for now. Thanks for the report!
