### ISSUE TITLE
[GNOME-Shell] don't enforce fonts on shell.

### ISSUE THREAD

**Issue by h4ndshake** [system76/pop-gtk-theme#23]
**Reporter info**

 * Distribution - `Ubuntu GNOME (System76 spin) 17.04, self compiled iso.`
 * Gtk+ 3.0 version - `3.22.11-0ubuntu3`
 * Desktop environment - `GNOME`

**Pop version (if you knew)**
`1.0.8`

**Related Application and/or Shell theming (or name of widget)**
`GNOME Shell`

**Actual issue**
Isn't best to not enforce fonts in GNOME Shell theming? and just let the user decides what fonts will be used..

https://github.com/system76/pop-gtk-theme/blob/master/shell/sass/gnome-shell/_common.scss#L21

**Comment by isantop** [comment]
This appears to actually be a limitation of GNOME Shell. Despite removing all font-related items in the CSS, the font can't be configured by the user or inherited from the GTK+ theme. Likely this is due to the disparity between GTK and ST (The toolkit that GNOME Shell is written in).
