### ISSUE TITLE
Gtk-WARNING about '-gtk-icon-filter' is not a valid property name

### ISSUE THREAD

**Issue by wangxa** [system76/pop-gtk-theme#24]
**Reporter info**

 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.22.15
 * Desktop environment - Gnome shell

**Pop version (if you knew)**
Commit 1eb5389

**Related Application and/or Shell theming (or name of widget)**
gtk3-widget-factory, gvim, etc.

**Actual issue**
(gvim:13696): Gtk-WARNING **: Theme parsing error: gtk-contained-dark.css:59:29: '-gtk-icon-filter' is not a valid property name

**Steps to reproduce (if you knew)**
1. Use gnome-tweak-tool to select Pop or Pop-Eta theme.
2. Use gnome-tweak-tool to enable the globle dark theme option,
3. Open gnome-terminal, and run `gtk3-widget-factory` or `gvim`

It seems `-gtk-icon-filter` is only supported after Gtk3 >= 3.89. So, you may have to change the `*:disabled { -gtk-icon-filter: opacity(0.5); }` to `*:disabled { -gtk-icon-effect: dim; }` in `pop-gtk-theme-master/gtk/sass/3.22/_common.scss`.

**Comment by isantop** [comment]
Thanks for catching that! Fixed!
