### ISSUE TITLE
nautilus issue

### ISSUE THREAD

**Issue by mozartilize** [system76/pop-gtk-theme#25]
**Reporter info**

```
 * Distribution - Ubuntu 17.04
 * Gtk+ 3.0 version - 3.22.11-0ubuntu3
 * Desktop environment - Gnome Shell 3.24
 * Pop version - 2.0.6.4
 ```
![selection_001](https://user-images.githubusercontent.com/26346270/29905450-0ac76d2e-8e39-11e7-9f55-42a67f66fdb7.png)

**Comment by isantop** [comment]
Can you get the version of nautilus you're using here? I don't get this issue on my end.

**Comment by mozartilize** [comment]
it's 3.20.4

**Comment by isantop** [comment]
After testing in 17.04, it appears this is being caused by Ubuntu Patches to Nautilus. The Nautilus present in the GNOME Staging PPA doesn't appear to have this problem, and the Nautilus present in 17.10 (Upon which the first stable release of Pop will be based) is also fine.
