### ISSUE TITLE
Properly ship a dark variant

### ISSUE THREAD

**Issue by TingPing** [system76/pop-gtk-theme#25]
Based upon this comment:

> To enable global dark theme, you use proper tools like Gnome-Tweak-Tool. Or add this porperty to [Settings] section of $HOME/.config/gtk-3.0/settings.ini:

This is not the proper way to have dark variants. This method cannot be used by Gtk2 (as your own readme points out) and cannot be used by sandboxed applications.

As other themes do they ship a dark variant like Adwaita-Dark, Breeze-Dark, Arc-Dark, etc.

**Comment by TingPing** [comment]
@isantop The theme directory should match the theme name.

**Comment by TingPing** [comment]
Also just FYI I've started packaging this theme for Flatpak: https://github.com/flathub/org.gtk.Gtk3theme.Pop

**Comment by isantop** [comment]
I think it's now correct. The Dark theme installs to $PREFIX/Pop-Dark and /Pop-Eta-Dark

**Comment by isantop** [comment]
Whoops, nevermind, there was an error with the Eta-Dark ones. This is now fixed in e3a16366
