### ISSUE TITLE
Change in theme colors due to synchronization with Adapta 

### ISSUE THREAD

**Issue by primetoxinz** [system76/pop-gtk-theme#26]
**Reporter info**

 * Distribution - ArchLinux
 * Gtk+ 3.0 version -  3.22.15-1
 * Desktop environment -  OpenBox *

**Pop version**
Previously 1.2.1, now 1.2.2 or higher

Due to the commit which synced with upstream Adapta, certain theme colors were changed.
For example, in openbox themerc, originally the main.border.color was  [#455A64](https://github.com/system76/pop-gtk-theme/blame/f9e32021b3172a5cab08970441582183e318afa0/wm/openbox-3/themerc#L2) yet as off the sync it is now [#574f4a](https://github.com/system76/pop-gtk-theme/blame/f9e32021b3172a5cab08970441582183e318afa0/wm/openbox-3/themerc#L2), a color actually used in Adapta.
This issue is prevalent all throughout the theme, not only in openbox, including all gtk window headers and backgrounds and much more.
It would be nice if this color was extracted into a global config, so if there were to happen again it would be a quick fix to simply change the config, I'm unsure how difficult that would be but just a suggestion.

**Comment by isantop** [comment]
Thanks for your report! The colors for most components actually are extracted from the _colors.scss and _key-colors.scss files at build-time. #574F4A is actually a System76-brand color, and is used as our Warm Grey, so this appears to be correct.

**Comment by primetoxinz** [comment]
Oh, it appears I put the wrong example. At some points throughout the theme there is a dark blue used often in Adapta. I'm kinda busy atm and can't reinstall 1.2.2 yet this was a picture of the preview in lxappearance when I had it installed 
https://imgur.com/a/yx4WJ

**Comment by primetoxinz** [comment]
This fixed the normal theme but not the dark theme
