### ISSUE TITLE
GNOME Settings selections should be orange (currently set to blue)

### ISSUE THREAD

**Issue by sarahpandabeara** [system76/pop-gtk-theme#28]

**Comment by jackpot51** [comment]
Thought I might look into this while granite is building

**Comment by jackpot51** [comment]
Committed fix in https://github.com/system76/pop-gtk-theme/commit/597cddcdef62d794f08fcd95392b158ccaf38363

**Comment by jackpot51** [comment]
https://launchpad.net/~system76/+archive/ubuntu/pop/+build/13372091
