### ISSUE TITLE
Switches in header bars: no visible trough when off

### ISSUE THREAD

**Issue by cassidyjames** [system76/pop-gtk-theme#29]
Probably should use a shade of brand warm gray, or a shade of white or something to ensure the switch trough stays visible on both dark and light backgrounds, when switched on or off.

**Comment by sarahpandabeara** [comment]
I'd loop in Kate on that one. She might have a good idea for what color to utilize between both themes.

**Comment by jackpot51** [comment]
Kate approved, and it has been committed

**Comment by cassidyjames** [comment]
@jackpot51 wait where is this code? Please mark commits as i.e. `fixes #29` so they get linked up, and the issue will automatically close when it gets merged into master.

**Comment by jackpot51** [comment]
I know that @cassidyjames, but it really isn't fixed when the commit happens. Only when the package hits the stable package repo
