### ISSUE TITLE
Red text in Terminal is hard to read

### ISSUE THREAD

**Issue by cassidyjames** [system76/pop-gtk-theme#3]
**Reporter info**

 ```
 * Distribution - Ubuntu GNOME 17.04
 * Gtk+ 3.0 version - 3.24
 * Desktop environment - GNOME Shell
 ```

**Related Application and/or Shell theming (or name of widget)**
Terminal

**Actual issue**
Default color scheme is hard to read red-on-background

**Steps to reproduce (if you knew)**
Use Pop, open GNOME Terminal, do something to print red text (like `git status` with untracked changes)

**Expected behaviour**
Red text doesn't hurt my head

**Other Note (feature-request, question, etc...)**
GNOME Terminal has a "use system colors" option checked.

**Comment by isantop** [comment]
Example: 

![screenshot from 2017-04-28 10-13-53](https://cloud.githubusercontent.com/assets/5883565/25685168/eb606af4-3022-11e7-8528-e1b7d47c89b7.png)

**Comment by isantop** [comment]
Improved in commit 14c27c4
