### ISSUE TITLE
[Feature Request] macOS Version

### ISSUE THREAD

**Issue by Modelmat** [system76/pop-gtk-theme#3]
Can this be supported on macOS ? It looks really cool and I would really like it on my Mac

**Comment by TingPing** [comment]
Themes aren't specific to any OS, it should work fine with Gtk on OSX.

**Comment by isantop** [comment]
Although it's worth noting that this won't work in macOS Apps or other programs using the native mac toolkits. It will only theme GTK apps on mac.

**Comment by Modelmat** [comment]
What I am asking, is would it work on the system apps etc.? (ie. are those GTK apps?)

**Comment by isantop** [comment]
No, those use the native macOS toolkit and are not aware of GTK or its theming.
