### ISSUE TITLE
font ligatures

### ISSUE THREAD

**Issue by jakehockey10** [system76/pop-gtk-theme#30]
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)

libgtk-3-0:
  Installed: 3.22.11-0ubuntu3
  Candidate: 3.22.11-0ubuntu3
  Version table:
 *** 3.22.11-0ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu zesty/main amd64 Packages
        100 /var/lib/dpkg/status


 * Desktop environment - 

 ```

**Pop version (if you knew)**

```
system76-default-settings/zesty,zesty 17.10.16 all
system76-desktop/zesty,zesty 1.0.2 all
system76-driver/zesty,zesty,now 17.04.5 all [installed]
system76-driver-nvidia/zesty,zesty,now 17.04.5 all [installed]
system76-pop-fonts/zesty,zesty,now 1.0.1 all [installed]
system76-pop-gtk-theme/zesty,zesty,now 1.3.1.1 all [installed]
system76-pop-icon-theme/zesty,zesty,now 1.1.4 all [installed]
system76-pop-theme/zesty,zesty 1.0.0 all
system76-wallpapers/zesty,zesty,now 17.04.0 all [installed,automatic]
```

**Related Application and/or Shell theming (or name of widget)**

Visual Studio Code

```
Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:16:25.899Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```
Settings:
```
// Place your settings in this file to overwrite the default settings
{
    "editor.fontFamily": "Fira Code",
    "editor.fontSize": 14,
    "editor.fontLigatures": true,
    "files.autoSave": "afterDelay",
    "window.zoomLevel": -1,
    "files.autoSaveDelay": 3000,
    "workbench.iconTheme": "vs-seti",
    "files.exclude": {
        "**/*.js": {
            "when": "$(basename).ts"
        },
        "**/*.map": {
            "when": "$(basename).map"
        }
    },
    "typescript.tsdk": "./node_modules/typescript/lib",
    "editor.formatOnSave": true,
    "html.format.wrapLineLength": 60,
    "html.format.wrapAttributes": "auto",
    "typescript.referencesCodeLens.enabled": true
}
```

**Actual issue**

I installed the pop theme a while back and remember having font ligatures working in Visual Studio Code.  But when I set the font suggested by the theme itself a while later, ligatures stopped working.  I hadn't read the font suggestions the first time installing the theme, so I had what was the default before making these font changes in the operating system until later.  I can't find a way to get font ligatures working, but I've downloaded and installed the fonts from [here](https://github.com/tonsky/FiraCode).

I've also tried launching visual studio code with `code . --disable-extensions` and the problem with not having font ligatures show up persisted.

I also tried the suggestion from the FiraCode GitHub repo in the link above in that if the ligatures don't show up, try `"'Fira Code'"` instead of `"Fira Code"`.

I also tried changing the operating system fonts to something not involving fira code font family at all, and restarting visual studio with `--disable-extensions`, with no change in behavior.

**Steps to reproduce (if you knew)**

- Install the latest Visual Studio Code.
- Install the Fira Code fonts by double clicking them from the download.
  - button in ubuntu window that pops up goes from "install" to "installed" a moment after opening.
- Apply the settings I have in my Visual Studio Code application.

**Expected behaviour**

I have no knowledge of why ligatures wouldn't work in general, so I'm cautiously assuming that this should work.  Another assumption I had due to trying many different things, trying to get this to work, and the timing, is that this is some sort of collision with the operating system font choices.

**Behaviour in Adwaita**

**Other Note (feature-request, question, etc...)**

I'm sorry if this isn't the right place for a report like this, but I didn't know where else to ask about this except for vscode's github repo.  I just searched for several days now, and I haven't been able to find anyone with the same problem using any editor for that matter.  I will likely report to vscode's repo as well, but I wasn't unsure that it was a collision with this theme.

**Comment by isantop** [comment]
I'm not sure this is an issue with the POP theme. Visual Studio Code is an electron app and thus not capable of being themed with GTK. Additionally, Pop no longer packages Fira Code in the `system76-pop-fonts` package, so this would seem to be an upstream issue with the Fira Code font. You'll want to open an issue there on [this page](https://github.com/tonsky/FiraCode/issues/).

**Comment by jakehockey10** [comment]
@isantop Fair points.  At first glance, this seemed like the right place because I have many other machines that this is not an issue with and I tried to narrow in on the differencesbetween them.

**Comment by jakehockey10** [comment]
I have opened an issue on vscode github page as well as the Fira Code github page.  Here is the Fira Code issue: https://github.com/tonsky/FiraCode/issues/435
