### ISSUE TITLE
Some image files are missing in GTK-2.0 themes

### ISSUE THREAD

**Issue by wangxa** [system76/pop-gtk-theme#31]
**Reporter info**

```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.22.15
 * Desktop environment - Gnome Shell
 ```

**Pop version (if you knew)**
1.3.1.r2

**Related Application and/or Shell theming (or name of widget)**
xscreensaver-demo

**Actual issue**
/usr/share/themes/Pop-Dark/gtk-2.0/3rd-party-dark.rc:180: Unable to locate image file in pixmap_path: "Xfce/flat-button.svg"
/usr/share/themes/Pop-Dark/gtk-2.0/3rd-party-dark.rc:183: Background image options specified without filename
/usr/share/themes/Pop-Dark/gtk-2.0/3rd-party-dark.rc:187: Unable to locate image file in pixmap_path: "Xfce/flat-button-hover.svg"
/usr/share/themes/Pop-Dark/gtk-2.0/3rd-party-dark.rc:190: Background image options specified without filename
/usr/share/themes/Pop-Dark/gtk-2.0/3rd-party-dark.rc:194: Unable to locate image file in pixmap_path: "Xfce/flat-button-active.svg"
/usr/share/themes/Pop-Dark/gtk-2.0/3rd-party-dark.rc:197: Background image options specified without filename
/usr/share/themes/Pop-Dark/gtk-2.0/3rd-party-dark.rc:201: Unable to locate image file in pixmap_path: "Xfce/flat-button-hover.svg"
/usr/share/themes/Pop-Dark/gtk-2.0/3rd-party-dark.rc:204: Background image options specified without filename

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Behaviour in Adwaita**

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
I can't seem to reproduce this issue on my end here. Running `xscreensaver-demo` doesn't result in any terminal output. I checked out a couple of other apps too, but none of them seem to cause this. Do you have the Pop-Dark theme set up in your `.gtkrc-2.0` file?

**Comment by wangxa** [comment]
I found the reason: when running the autogen.sh, I passed '--disable-xfce' to it, which will copy the image files to the Xfce directory. So would you add the dependency of '--enable-xfce' when gtk-2.0 is enabled?

**Comment by isantop** [comment]
GTK 2 support is always built to ensure backwards compatibility with applications like Gimp and Inkscape. On the other hand, XFCE support isn't always needed, and not including that will result in a slightly smaller footprint for the theme if someone builds it that way. I don't think that requiring XFCE support is a good choice.

**Comment by wangxa** [comment]
But files under Xfce directory will not be installed if '--disable-xfce' is specified. Anyway, depend on you.
