### ISSUE TITLE
Dark theme has problems on Firefox

### ISSUE THREAD

**Issue by ryanleesipes** [system76/pop-gtk-theme#32]
```
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

libgtk-3-0:
  Installed: 3.22.11-0ubuntu3
  Candidate: 3.22.11-0ubuntu3
  Version table:
 *** 3.22.11-0ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu zesty/main amd64 Packages
        100 /var/lib/dpkg/status

 GNOME (Via Ubuntu GNOME 17.04)
 ```

Pop Version: From unstable channel

Using Pop Slim Dark

Firefox looks weird with Pop Dark themes:

Blue text hard to see on drop down:
![screenshot from 2017-06-16 11-16-32](https://user-images.githubusercontent.com/2141621/27237194-63cc4cae-5285-11e7-8593-b23e801af115.png)

Text box in Google Drive (and random other places) looks out of place and hard to read:
![screenshot from 2017-06-16 11-17-06](https://user-images.githubusercontent.com/2141621/27237193-63cad5fe-5285-11e7-9c89-aabd63bd0d42.png)

**Comment by ryanleesipes** [comment]
Another couple of examples of text entry:

![screenshot from 2017-06-16 11-33-53](https://user-images.githubusercontent.com/2141621/27237877-f52515e4-5287-11e7-818f-89eebe2034ae.png)
![screenshot from 2017-06-16 11-35-10](https://user-images.githubusercontent.com/2141621/27237876-f524a23a-5287-11e7-94a6-f68354cd4cce.png)

**Comment by ryanleesipes** [comment]
Another weird textbox issue.

![screenshot from 2017-06-16 12-01-49](https://user-images.githubusercontent.com/2141621/27238861-cf877a44-528b-11e7-9901-cf3043032e67.png)

**Comment by isantop** [comment]
These types of issues also happen in Adwaita-Dark. This is due to lazy web programming and poor decisions on the part of Firefox. It can't be fixed in the GTK Theme
