### ISSUE TITLE
Shell OSD bars pixelated on HiDPI

### ISSUE THREAD

**Issue by cassidyjames** [system76/pop-gtk-theme#32]
Bars for the on-screen-display UI in Shell (i.e. brightness or volume confirmation) are pixelated in HiDPI.

Latest version of the theme as of right now on Pop!_OS 17.10.

![screenshot from 2017-09-22 10-25-24](https://user-images.githubusercontent.com/611168/30754557-685a74b0-9f80-11e7-9cce-fce886a4f6a3.png)
![screenshot from 2017-09-22 10-23-59](https://user-images.githubusercontent.com/611168/30754554-67e282fc-9f80-11e7-8ddd-a6ded816ae13.png)

**Comment by cassidyjames** [comment]
This is not _always_ reproducible. I'm not sure what causes it but it happens frequently. :man_facepalming:

**Comment by isantop** [comment]
Can't seem to reproduce, and this widget is drawn using CSS, so there shouldn't be any pixels to make larger. Closing for now, since this seems to be a GNOME Shell bug if anything.
