### ISSUE TITLE
I can not install on Ubuntu 16.04

### ISSUE THREAD

**Issue by DiegusMiestro** [system76/pop-gtk-theme#33]
Hello,

I installed it on my work computer, using PPA, but at home I can not install the theme. Adds the PPA, I make the update and when ordering to install, it appears the message that the package was not found.

**Comment by Orizon98** [comment]
Hello, install with this command:
sudo apt-get install system76-pop-icon-theme
sudo apt-get install system76-pop-gtk-theme
sudo apt-get install system76-pop-theme

**Comment by DiegusMiestro** [comment]
@Orizon98 
I tried, but it did not work either. I add the PPA as it says to be done here on Github.
In my work it worked well, but when I went to install at home, says that it is impossible to find the package.

**Comment by jackpot51** [comment]
The command should be:
```
sudo apt install pop-theme
```

**Comment by boris-savic** [comment]
Same problem. Added official ppa as described in readme, error log says the package cannot be found.

Fresh installation of Ubuntu Gnome 16.04

**Comment by isantop** [comment]
@boris-savic @DiegusMiestro The full command sequence to install the Pop theme in Ubuntu (16.04+) is:

```
sudo add-apt-repository ppa:system76/pop
sudo apt update
sudo apt install pop-theme 
```

If this doesn't work, please reopen this issue and comment with the output you're getting.
