### ISSUE TITLE
Insensitive entries in headerbars are non-distinct

### ISSUE THREAD

**Issue by cassidyjames** [system76/pop-gtk-theme#34]
Insensitive entries in headerbars are not clearly distinct from sensitive ones; they appear to retain the same opacity and colors. Adwaita grays them out a little bit, while elementary is a bit more drastic.

I noticed this specifically in Pop!_Shop/AppCenter, but it affects any app (confirmed by using inspector to mark the search entry in GNOME Maps as insensitive).

# Screenshots

In these screenshots, the entry is sensitive on the Home screen, but insensitive on the Updates screen.

## Pop

![appcenter-home-pop](https://user-images.githubusercontent.com/611168/30979598-5b28ff0e-a43b-11e7-9a13-3314c7744335.png)

![appcenter-updates-pop](https://user-images.githubusercontent.com/611168/30979606-63a13732-a43b-11e7-8d36-0dfa2e99b205.png)

## Adwaita

![appcenter-home-adwaita](https://user-images.githubusercontent.com/611168/30979617-69fe77c0-a43b-11e7-8f7e-bd2c145125ed.png)

![appcenter-updates-adwaita](https://user-images.githubusercontent.com/611168/30979618-6c0d4960-a43b-11e7-81c7-b2a35b517bbc.png)

## elementary

![appcenter-home-elementary](https://user-images.githubusercontent.com/611168/30979629-72b1838a-a43b-11e7-8473-3e9b6360f2a9.png)

![appcenter-updates-elementary](https://user-images.githubusercontent.com/611168/30979633-74a6afd0-a43b-11e7-9bb0-ad77d953e4ba.png)

**Comment by isantop** [comment]
Fixed in 7c235f1fdb0b5e355f41954ff6e7686c30bce41e
