### ISSUE TITLE
Install via Flatpak (theme for Flatpak apps)

### ISSUE THREAD

**Issue by ryanleesipes** [system76/pop-gtk-theme#35]
Please include information on how to install the theme for use with Flatpak apps in the README.

**Comment by TingPing** [comment]
Instructions btw:

```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.gtk.Gtk3theme.Pop
```

See also for more details: https://tingping.github.io/2017/05/11/flatpak-theming.html

**Comment by isantop** [comment]
I'm mixed on this. We're likely going to include the FlatPak version of Pop in the distro by default, and I want to avoid overdocumenting everything. Flathub has some excellent documentation, and simply pointing folks there is probably a better way to handle this, and it doesn't require as much maintenance on our end to ensure the documentation is up to date.

**Comment by TingPing** [comment]
The end goal is that `gnome-software` handles installing themes automatically, doing it manually is just the immediate solution.

**Comment by ryanleesipes** [comment]
@TingPing is slim included in there? ^

**Comment by TingPing** [comment]
Not currently. It is mildly annoying to package 4 variants of a single theme. If you guys want to deal with updating it though I can create the repos for them and add you.

**Comment by ryanleesipes** [comment]
@TingPing once it is installed what action do I have to take to apply it? Using Corebird and it is not Popified.

**Comment by TingPing** [comment]
@ryanleesipes See the notes section on my blog post I linked, but specifically you are using a build of corebird against an old gnome runtime that never got that update. Corebird is in flathub though built against the latest.

**Comment by ryanleesipes** [comment]
This works. Do you know what the plan is with Flathub? Will that ultimately be the defacto way of uploading and sharing applications?

**Comment by TingPing** [comment]
Yes, eventually all the GNOME apps will probably move to flathub too.

**Comment by ryanleesipes** [comment]
This can be closed. All of this appears to be good and make sense.
