### ISSUE TITLE
Shadow of the button are cutted

### ISSUE THREAD

**Issue by Corsseir** [system76/pop-gtk-theme#36]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - Pop!_OS BETA
 * Gtk+ 3.0 version - Pop!_OS BETA
 * Desktop environment - GNOME 3.26
 * Pop version - The newest
 ```

**Related Application and/or Shell theming (or name of widget)**
Gnome-Photos

**Actual issue**
Shadow ot the buttons are cutted.

**Steps to reproduce**
Just install Gnome Photos and open some photo with light background

**Expected behavior**
I think I don't have to explain it :) 

**Behavior in Adwaita**
Excellent

**Other Note (feature-request, question, etc...)**

![1](https://user-images.githubusercontent.com/11137173/31138473-e63271ac-a86e-11e7-9ae0-609979989414.png)
![2](https://user-images.githubusercontent.com/11137173/31138478-e9505408-a86e-11e7-8dff-25b59d23e864.png)

**Comment by isantop** [comment]
Can you let me know what version of the Pop theme you have installed? I don't presently have this issue with the latest Pop theme from git, and this is a bug that was [fixed several versions ago](https://github.com/system76/pop-gtk-theme/issues/10).

**Comment by isantop** [comment]
Closing due to no response in one week.

**Comment by Corsseir** [comment]
I use the newest one from repo with Pop OS
