### ISSUE TITLE
Telegram Nokto Theme Doesn't Look Very "Poppy"

### ISSUE THREAD

**Issue by ryanleesipes** [system76/pop-gtk-theme#36]
**Pop version (if you knew)**
Pulled from Master

**Related Application and/or Shell theming (or name of widget)**
Telegram application

**Actual issue**
Telegram "Nokto" (Dark) theme doesn't look very "Poppy"

**Steps to reproduce (if you knew)**
Load the Telegram Pop Nokto theme

![screenshot from 2017-06-20 10-10-39](https://user-images.githubusercontent.com/2141621/27344233-e03141b2-55a2-11e7-917e-40424dfdf8e0.png)

**Expected behaviour**
Expected it to be more brown and in keeping with our dark theme.

**Comment by isantop** [comment]
Telegram isn't an App we include by default, so this is very low-priority. Otherwise, patches welcome.

**Comment by ryanleesipes** [comment]
Alright, I'll see what I can do.

**Comment by ryanleesipes** [comment]
Working on this, will have something to send by the EOW.

**Comment by ryanleesipes** [comment]
I've begun work on this in #37  - I will address Light/Dark once I have more experience with theming Telegram. The current one is listed as "Light" but it more likely should be Dark/Nokto.
