### ISSUE TITLE
Strange background around headbar buttons

### ISSUE THREAD

**Issue by Corsseir** [system76/pop-gtk-theme#37]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - Pop!_OS BETA
 * Gtk+ 3.0 version - Pop!_OS BETA
 * Desktop environment - GNOME 3.26
 * Pop version - The newest
 ```

**Related Application and/or Shell theming (or name of widget)**
EoG

**Actual issue**
Strange background around headbar buttons.

**Steps to reproduce**
Just open some image in EoG (Eye of Gnome I guess).

**Expected behavior**
I think I don't have to explain it :) 

**Behavior in Adwaita**
Excellent

**Other Note (feature-request, question, etc...)**

![3](https://user-images.githubusercontent.com/11137173/31138529-1b121fa8-a86f-11e7-9159-f76ed4bf4778.png)

**Comment by isantop** [comment]
The circle background behind the + button isn't a theme bug, but seems to be a bug in Eye of GNOME where that particular button isn't set as flat, so it has a background drawn all the time. That's unfortunately not something I can fix without breaking the styling for _all_ image-button items in the theme. 

However, the underline is definitely a theme bug and can be fixed.
