### ISSUE TITLE
Chrome and GTK2: low contrast on text and icons

### ISSUE THREAD

**Issue by Feichtmeier** [system76/pop-gtk-theme#38]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - Description:	Ubuntu Artful Aardvark (development branch)
Release:	17.10
 * Gtk+ 3.0 version - 3.22.21-0ubuntu1

 * Desktop environment - GNOME
 * Pop version - 2.1.1.11

 ```

**Related Application and/or Shell theming (or name of widget)**
Google Chrome Version 61.0.3163.100
Inkscape  0.92.2 (and probably more gtk2 apps)

**Actual issue**
Low contrast on text and icons

![bildschirmfoto von 2017-10-03 19-09-11](https://user-images.githubusercontent.com/15329494/31138545-261bd330-a86f-11e7-9bdd-e1a1fc764c38.png)
![bildschirmfoto von 2017-10-03 19-08-54](https://user-images.githubusercontent.com/15329494/31138547-26243ce6-a86f-11e7-931b-e0aa313be25b.png)
![bildschirmfoto von 2017-10-03 19-08-49](https://user-images.githubusercontent.com/15329494/31138546-2622d8ec-a86f-11e7-97a4-0aa478dabf3c.png)

**Steps to reproduce**

**Expected behavior**

**Behavior in Adwaita**

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
Can you get the version of Chrome you're using from the Menu > Help > About Google Chrome ?

**Comment by Feichtmeier** [comment]
The version is
61.0.3163.100

**Comment by isantop** [comment]
Unfortunately, little can be done about GTK2 (particularly inkscape) due to the fact that GTK2 icons cannot be recolored dynamically by the theme the way they can be for GTK3. Making the icons darker to help contrast in GTK2 breaks this ability for GTK3 as well, thus compromising the usability there as well.
