### ISSUE TITLE
Support for Ubuntu 16.04

### ISSUE THREAD

**Issue by justinnichols** [system76/pop-gtk-theme#4]
The README states nothing about which versions of Ubuntu are supported.  I had to install the PPA simply to see that xenial is not supported on that PPA.  I also verified that the pop theme has been removed from the system76 stable PPA.

Is there any plan to support Ubuntu 16.04 for the pop-gtk-theme?  Is there a different PPA that supports xenial for the pop-gtk-theme (than the one listed in the README)?

If the answer is no to both of those questions, how then would one get the pop-gtk-theme installed on xenial?  I attempted to install from source, but the prerequisite sassc isn't available in the default repos of xenial.

**Comment by isantop** [comment]
The Debian packages attached to the [Github Releases](https://github.com/system76/pop-gtk-theme/releases/latest) should be compatible with 16.04. We'll investigate adding the packages to the xenial repo, perhaps as an unsupported option.

**Comment by justinnichols** [comment]
It does indeed.  Thank you!  This .deb package is probably good enough until 18.04 is released, but of course it won't see updates as if it was in a repo for xenial.  Thanks for looking into the possibility of it being put in a repo even if in a non-supported fashion.

**Comment by isantop** [comment]
As of 2.0.3, the theme is being copied into xenial. Please note that the rest of Pop is not being developed with 16.04 in mind and won't work. Also note that GNOME 3.18 is not tested and there may be theme bugs. Any bugs filed against GNOME 3.18 will be backburnered and fixed when convenient, and will not be high-priority. However, this should allow you to get updates automatically.

**Comment by justinnichols** [comment]
Thanks so much, @isantop !
