### ISSUE TITLE
Transparent background of the virtual desktops

### ISSUE THREAD

**Issue by Corsseir** [system76/pop-gtk-theme#41]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
 * Desktop environment - 
 * Pop version - (run ```apt policy pop-gtk-theme```)
 ```

**Related Application and/or Shell theming (or name of widget)**
Gnome Shell

**Actual issue**
Transparent background of the virtual desktops.

**Steps to reproduce**
Just open dash.

**Expected behavior**
I believe that brown background with round corners like in application dock would be look much better.

**Behavior in Adwaita**
Excellent

**Other Note (feature-request, question, etc...)**

![5](https://user-images.githubusercontent.com/11137173/31138828-034397d4-a870-11e7-9350-92ad24b3b714.png)

**Comment by WatchMkr** [comment]
For this one, the dash should be on a transparent background. Elements on the Activities view are typically hovering in space rather than boxed in (Search, Search results, and Windows). I think the Dash and Workspaces should have the same treatment.
