### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by idarlington** [system76/pop-gtk-theme#42]
**Reporter info**

 * Distribution 

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

 * Gtk+ 3.0 version

```
libgtk-3-0:
  Installed: 3.18.9-1ubuntu3.3
  Candidate: 3.18.9-1ubuntu3.3
  Version table:
 *** 3.18.9-1ubuntu3.3 500
        500 http://ng.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.18.9-1ubuntu3 500
        500 http://ng.archive.ubuntu.com/ubuntu xenial/main amd64 Packages

```

 * Desktop environment 
```
Ubuntu 16.04
```

**Actual issue**

I have this issue when I try to install the pop theme. This occurs even after installing the ppa and restarting.
This is the error 

```
E: Unable to locate package pop-theme
```

**Comment by isantop** [comment]
What are the exact commands you ran to add the PPA and install the theme?

**Comment by idarlington** [comment]
@isantop  same commands available in the docs

```
sudo add-apt-repository ppa:system76/pop
sudo apt update
sudo apt install pop-theme
```

**Comment by jackpot51** [comment]
@idarlington I have updated the xenial packages, can you try:
```
sudo apt update
sudo apt install pop-theme
```
again?

**Comment by idarlington** [comment]
Thanks @jackpot51 it works now. What was the issue?

**Comment by jackpot51** [comment]
We did not have all of the dependencies on Xenial.

**Comment by jose-sanchezm** [comment]
I've tried to install it on elementaryOS Loki (which is based on Xenial) but I got this error:

The following packages have unmet dependencies:
 pop-gtk-theme : Depends: gnome-themes-standard (>= 3.18.9) but 3.18.0-2ubuntu1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by idarlington** [comment]
@jose-sanchezm you would need to update gnome

```

**Comment by macagoraga** [comment]
I am getting this same issue, there is a fix?


$ sudo apt update

Hit:1 http://ch.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease              
Hit:3 http://ch.archive.ubuntu.com/ubuntu xenial-updates InRelease             
Hit:4 http://ch.archive.ubuntu.com/ubuntu xenial-backports InRelease           
Hit:5 http://ppa.launchpad.net/system76/pop/ubuntu xenial InRelease            
Hit:6 https://deb.nodesource.com/node_8.x xenial InRelease                     
Hit:7 http://security.ubuntu.com/ubuntu xenial-security InRelease              
Hit:8 https://download.sublimetext.com apt/stable/ InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
11 packages can be upgraded. Run 'apt list --upgradable' to see them.

$ sudo apt install pop-theme

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package pop-theme

$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
