### ISSUE TITLE
Arch Install "error: 'gnome-shell' not found"

### ISSUE THREAD

**Issue by natemaia** [system76/pop-gtk-theme#46]
**Reporter info**

```
Distribution - Arch
WM - Openbox
 ```

**Actual issue**
Is it possible to have an install that doesn't require Gnome Shell?
I realize this is a Gnome based theme, but I really love it and recently I cannot install via AUR.
After cloning from git and removing the Gnome Shell check in configure.ac, it installed correctly with one error regarding gnome shell.
If installing in other environments isn't something you wish to support then my apologies and you may disregard & close this issue.

**Steps to reproduce (if you knew)**

Attempt install in non-Gnome environment results in the following error:

checking for gnome-shell... no
configure: error: 'gnome-shell' not found.

**Other Note**

Thank you guys so much for making this theme and everything else you do for the open source communities, it is appreciated.

Regards, 
Nathaniel

**Comment by primetoxinz** [comment]
Also on Arch, I found that adding `--disable-gnome` to the `./autogen.sh` lines in the PKGBUILD fixes the error

**Comment by natemaia** [comment]
This is very helpful, thank you @primetoxinz
