### ISSUE TITLE
firefox tabs are not themed 

### ISSUE THREAD

**Issue by xeon-zolt** [system76/pop-gtk-theme#47]
**Reporter info**

```
 * Arch Linux
 * Gtk+ 3.0 version - 3.22.16
 * Desktop environment - Gnome 3.24.2
 * Pop version - 
 ```

**Related Application and/or Shell theming (or name of widget)**

firefox

**Actual issue**
it is not looking like it should look like

**Steps to reproduce (if you knew)**

used gnome tweak tool to apply slim dark theme

**Expected behaviour**
theme should be applied correctly for the firefox browser

**Behaviour in Adwaita**

it works fine 

**Other Note (screenshot )**
check the tabs part 

![screenshot from 2017-07-05 20-43-42](https://user-images.githubusercontent.com/4529442/27871631-d6efe2ca-61c3-11e7-9f91-e440596319b1.png)

**Comment by JosephMcc** [comment]
Did you try closing and restarting Firefox? This has always been an issue when changing themes.

**Comment by xeon-zolt** [comment]
fixed 
thanks @JosephMcc 
i also noticed some other colors not working perfectly will try after restarting shell
