### ISSUE TITLE
Buttons cut of in a gtk dialogue window in Geary Mail

### ISSUE THREAD

**Issue by Feichtmeier** [system76/pop-gtk-theme#5]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - Ubuntu GNOME 17.04
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - GNOME
 * Pop version - 2.0.1.0
 ```

**Related Application and/or Shell theming (or name of widget)**
Geary Mail

**Actual issue**
![bildschirmfoto vom 2017-08-10 14-26-13](https://user-images.githubusercontent.com/15329494/29170291-2708d5ca-7dd8-11e7-80c9-6870ff766f53.png)
![bildschirmfoto vom 2017-08-10 14-29-23](https://user-images.githubusercontent.com/15329494/29170339-61f675f2-7dd8-11e7-83a0-2ede358c158f.png)
![bildschirmfoto vom 2017-08-10 14-30-44](https://user-images.githubusercontent.com/15329494/29170364-86f7322e-7dd8-11e7-91fd-84f335ffe54f.png)

The buttons are cut of at the bottom in geary when you add another account.

**Steps to reproduce**
Install Geary Mail, add an account.

**Expected behavior**
Not the whole buttons are visible

**Behavior in Adwaita**
The buttons show completly

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
Just needed to add some padding. Looks much better in the new commit. Thanks for your report!

**Comment by Feichtmeier** [comment]
Sadly, this issue remains with pop gtk version 2.0.5.0 on ubuntu 17.04 GNOME

![bildschirmfoto von 2017-08-15 20-49-13](https://user-images.githubusercontent.com/15329494/29331025-6ed96c44-81fb-11e7-84e5-9d60ec181244.png)

**Comment by isantop** [comment]
I can't reproduce it on my end. What version of Geary are you using? Also, try rebooting your machine to ensure that the absolute latest version of the theme is loaded.

**Comment by Feichtmeier** [comment]
Geary version is 0.11.3 (if you are on 16.04 you need their ppa for that, for 16.10+ it's in the official repos)

**Comment by isantop** [comment]
This is what I'm seeing: 

![screenshot from 2017-08-15 13-04-55](https://user-images.githubusercontent.com/5883565/29331656-6ce3a666-81ba-11e7-8be0-d01ddcbf0d38.png)

If yours still doesn't match after rebooting, please update your system to version 2.0.5.1 of the Pop theme (should be available in the repo shortly), then paste me the output of:
```
head -5 /usr/share/themes/Pop/gtk-3.22/gtk.css
```
And give it another test.

**Comment by Feichtmeier** [comment]
![bildschirmfoto von 2017-09-05 16-25-58](https://user-images.githubusercontent.com/15329494/30066063-151adf46-9257-11e7-8c78-7498687d194e.png)

I am on ubuntu 17.10 now, too. Still in geary and in gnome calendar the buttons are a bit cut off. Using 
 2.1.1.0 pop gtk theme
gtk3 3.22.19
