### ISSUE TITLE
Improve gnome-terminal default (light) theme

### ISSUE THREAD

**Issue by WatchMkr** [system76/pop-gtk-theme#53]
Change tabs to match
Change sidebar to fit in

**Comment by isantop** [comment]
Is this the same issue issue #40 ? If so, I think this is better solved by setting GNOME Terminal to use the dark theme by default since "fixing" that would be hacking the light theme to use the dark theme styling for GNOME Terminal.

**Comment by WatchMkr** [comment]
The dark theme header bar is too dark and menu's don't match with the rest of the desktop.

The terminal is important enough that investing in getting the light variant correct is worth it.

**Comment by isantop** [comment]
Relevant screenshots in Adwaita and Adapta

![screenshot from 2017-10-10 10-19-37](https://user-images.githubusercontent.com/5883565/31397944-a0a587d8-ada4-11e7-82f7-2cea6b79ba9a.png)

![screenshot from 2017-10-10 10-19-21](https://user-images.githubusercontent.com/5883565/31397951-a6435490-ada4-11e7-8c93-a3ca1aa5de3c.png)

**Comment by isantop** [comment]
Fixed in 38d43079baf6b0ba25816c928a60b2379ca1b337
