### ISSUE TITLE
GDM incorrect password text has insufficient contrast with background

### ISSUE THREAD

**Issue by jbicha** [system76/pop-gtk-theme#59]
**Reporter info**

 * Distribution - Pop!_OS 17.10 (installed a few weeks ago, updated)
 * Gtk+ 3.0 version - 3.22.21
 * Desktop environment - GNOME/Pop 
 * Pop version - 2.1.2.1 

**Related Application and/or Shell theming (or name of widget)**
 * gdm3 3.26.1
 * gnome-shell 3.26.1

**Steps to reproduce**
On the login screen, enter the wrong password

**Actual issue**
The "Sorry that didn't work message" is deep red on gray.

**Expected behavior**
There is more contrast between the text and its background so that the message is easier to read.

**Comment by isantop** [comment]
In the past when trying to style that text, it hasn't updated. Do you happen to know the correct CSS selector for that widget?

**Comment by jbicha** [comment]
Sorry, no.

**Comment by jackpot51** [comment]
@isantop I had fixed that here: https://github.com/system76/pop-gtk-theme/commit/2afc413c593f21c35cfb8c35bf651313fa032f90

Is this still in?

**Comment by isantop** [comment]
Looks like it just was too dark. On the bright side, I now know the selector to use and can fix it easily.

**Comment by jbicha** [comment]
> Looks like it just was too dark. On the bright side

:grin:

**Comment by isantop** [comment]
This will be released to stable along with 2.2
