### ISSUE TITLE
Wrong color of the status bar in Gnome control center's power 

### ISSUE THREAD

**Issue by wangxa** [system76/pop-gtk-theme#6]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - Fedora
 * Gtk+ 3.0 version - 3.24
 * Desktop environment - Gnome
 * Pop version - 2.0.3.0
 ```

**Related Application and/or Shell theming (or name of widget)**
gnome-control-center 

**Actual issue**
The color of the batteries in the Power page is black. I think it is incorrect.

![screenshot from 2017-08-10 13-49-24](https://user-images.githubusercontent.com/1250269/29171531-c3a0d4ea-7dd4-11e7-8bbb-d45f862d895e.png)
 
![screenshot from 2017-08-10 13-58-47](https://user-images.githubusercontent.com/1250269/29171538-c882dc88-7dd4-11e7-948e-4958b51341f1.png)

![screenshot from 2017-08-10 13-59-15](https://user-images.githubusercontent.com/1250269/29171540-cbe70fde-7dd4-11e7-8c17-cf8a886771d1.png)

**Steps to reproduce**
run `gnome-control-center` and click `Power`  

**Expected behavior**

**Behavior in Adwaita**

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
Thanks for pointing that out! It looks like levelbars were set to use a different color when "full", which is what caused this. I've unset that rule and it should prevent this from coming up again.
