### ISSUE TITLE
Gedit has white highlight over white text with global dark theme turned on

### ISSUE THREAD

**Issue by Xeboc** [system76/pop-gtk-theme#7]
**Reporter info**

 ```
 * Distribution - Ubuntu GNOME 17.04
 * Gtk+ 3.0 version - 3.22.11-0ubuntu3
 * Desktop environment - GNOME Shell
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**
Global Dark Theme

**Actual issue**
Gedit has default highlighting of white over near-white text when global dark theme is selected in the tweak tool.

**Steps to reproduce (if you knew)**
Install theme, set GTK+, Icons, Cursor, and Shell Theme to Pop, and turn on Global Dark Theme.  Open Gedit and type some text.

**Expected behaviour**
Text is readable in Gedit while highlighted.

**Other Note (feature-request, question, etc...)**

![screenshot_2017-04-28_17-29-18](https://cloud.githubusercontent.com/assets/11683321/25550745/0476010e-2c39-11e7-897f-1b63ba95b7a2.png)

**Comment by isantop** [comment]
This appears to be a problem with the current-line highlight feature, since selected text here has a blue BG. Will have to look at where to set this color.

**Comment by isantop** [comment]
This also happens in Adwaita, so I think it's just a GTK bug. 
![screenshot from 2017-05-03 16-48-39](https://cloud.githubusercontent.com/assets/5883565/25684785/7f504944-3020-11e7-9cce-6180ed97b571.png)
