### ISSUE TITLE
Message Dialog buttons don't respect suggested-action or destructive action classes

### ISSUE THREAD

**Issue by djordan2** [system76/pop-gtk-theme#7]
When setting a button to have a suggested-action or destructive-action class in regular windows, the styling changes to reflect this.  In a message dialog's buttons, setting either class doesn't change color.  

There is no indication that an action is suggested or destructive.  

In Adwaita, suggested message dialog buttons are blue and destructive ones are red.

**Comment by isantop** [comment]
Closing for now, since suggested actions in messagedialog class button boxes is not a standard GTK Development/layout practice.
