### ISSUE TITLE
Chrome button bug

### ISSUE THREAD

**Issue by Corsseir** [system76/pop-gtk-theme#8]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - Ubuntu 17.04
 * Gtk+ 3.0 version - 3.22.11-0ubuntu3
 * Desktop environment - GNOME (GNOME Shell)
 * Pop version - 2.0.4.2
 ```

**Related Application and/or Shell theming (or name of widget)**
Chrome

**Actual issue**
Weird black color of the button angles and background of the button is pretty the same as popup background.

![1](https://user-images.githubusercontent.com/11137173/29239302-e5308736-7f4b-11e7-89f3-de51d7b2890e.png)

**Steps to reproduce**

**Expected behavior**

**Behavior in Adwaita**

**Other Note (feature-request, question, etc...)**

**Comment by Corsseir** [comment]
The weird black bottom left and right corners still persist.

**Comment by isantop** [comment]
What version of Chrome/Chromium are you using? I'm not seeing it in Chrome 60.0.3112.101
