### ISSUE TITLE
ubuntu xenial packages

### ISSUE THREAD

**Issue by denikris** [system76/pop-gtk-theme#9]
it said "E: Unable to locate package system76-pop-theme" after try install with apt

**Comment by isantop** [comment]
The packages were currently built only for Ubuntu 17.04, but they should also work without modifications on 16.04 as well. There should be Xenial packages available in the repository within a couple of hours. Please try `sudo apt update && sudo apt install system76-pop-theme` then and let us know if you continue to have issues.

**Comment by AnthonyWC** [comment]
It hasn't been updated for xenial https://launchpad.net/~system76/+archive/ubuntu/pop

**Comment by isantop** [comment]
Supporting Xenial requires carrying support for Gtk 3.18. There are some talks internally about switching internal infrastructure around to help achieve this, but in the meantime you can download the latest support Xenial version here: https://github.com/system76/pop-gtk-theme/releases/tag/v1.3.1.2
